spring:
    application:
        name:
            aiChat

#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
#      api-key: ${GEMINI_API_KEY}
#      model-name: gemini-2.0-flash
#      log-requests: true
#      log-responses: true
#    streaming-chat-model:
#      base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
#      api-key: ${GEMINI_API_KEY}
#      log-requests: true
#      log-responses: true
#      model-name: gemini-2.0-flash
langchain4j:
  google-ai:
    gemini:
      model-name: gemini-2.0-flash
      api-key: ${GEMINI_API_KEY}
      streaming: true


logging:
  level:
    org.springframework: DEBUG
    dev.langchain4j: DEBUG

